spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:http://localhost:8888

rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

server:
  port: 8082

logging:
  level:
    org.springframework.amqp: DEBUG