spring:
  application:
    name: activity-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://configserver:8888}
  data:
    mongodb:
      uri: ${ACTIVITY_MONGODB_URI:mongodb://mongodb:27017/fitness_activities_db}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

server:
  port: ${ACTIVITY_SERVICE_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

logging:
  level:
    org.springframework.amqp: DEBUG