# Activity Service Configuration
# Managed by Config Server

spring:
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:true}
  
  data:
    mongodb:
      uri: ${MONGO_URI:${MONGO_URI_ACTIVITY:mongodb+srv://activity_db_user:${MONGO_ACTIVITY_PASSWORD}@fitapp.awbcqor.mongodb.net/activity_db?retryWrites=true&w=majority&tls=true&appName=FitApp}}
  
  rabbitmq:
    addresses: ${RABBITMQ_URI}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}
    listener:
      simple:
        missing-queues-fatal: false
        auto-startup: ${RABBITMQ_LISTENER_AUTO_START:true}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP:false}

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE:activity.exchange}
  queue:
    name: ${RABBITMQ_QUEUE:activity.queue}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:activity.tracking}
