# AI Service Configuration
# Managed by Config Server

spring:
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:true}
  
  data:
    mongodb:
      uri: ${MONGO_URI:${MONGO_URI_AI:mongodb+srv://ai_db_user:${MONGO_AI_PASSWORD}@fitapp.awbcqor.mongodb.net/ai_db?retryWrites=true&w=majority&tls=true&appName=FitApp}}
  
  rabbitmq:
    addresses: ${RABBITMQ_URI}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${RABBITMQ_SSL_ENABLED:true}
    listener:
      simple:
        missing-queues-fatal: false
        auto-startup: ${RABBITMQ_LISTENER_AUTO_START:true}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP:false}

rabbitmq:
  exchange:
    name: ${AI_RABBITMQ_EXCHANGE:${RABBITMQ_EXCHANGE:activity.exchange}}
  queue:
    name: ${AI_RABBITMQ_QUEUE:${RABBITMQ_QUEUE:activity.queue}}
  routing:
    key: ${AI_RABBITMQ_ROUTING_KEY:${RABBITMQ_ROUTING_KEY:activity.tracking}}
  listener:
    auto-startup: ${RABBITMQ_LISTENER_AUTO_START:true}

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
