server:
  port: ${USER_SERVICE_PORT:8080}

spring:
  application:
    name: user-service
  config:
    import: optional:${SPRING_CONFIG_IMPORT:configserver:http://localhost:8888}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration
  datasource:
    url: jdbc:postgresql://ep-small-truth-ahb8e4vi-pooler.c-3.us-east-1.aws.neon.tech/user_db?sslmode=require&currentSchema=user_schema
    username: neondb_owner
    password: npg_CLRh6Z5OFUGm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    schemas: user_schema
    locations: classpath:db/migration
    baseline-on-migrate: true

  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: ${EUREKA_PREFER_IP:false}
