spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}/

app:
  auth0:
    audience: ${AUTH0_AUDIENCE}

emailjs:
  service-id: ${EMAILJS_SERVICE_ID}
  template-id: ${EMAILJS_TEMPLATE_ID}
  public-key: ${EMAILJS_PUBLIC_KEY}
  template-admin: ${EMAILJS_TEMPLATE_ADMIN}
  template-user: ${EMAILJS_TEMPLATE_USER}
