server:
  port: 8085

spring:
  application:
    name: api-gateway
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://configserver:8888}

  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://configserver:8888}
      fail-fast: false
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  # OAuth2 Resource Server Configuration

eureka:
  instance:
    hostname: ${EUREKA_HOST:api-gateway}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

# CORS Configuration
management:
  endpoints:
    web:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true
