spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888


# Application configuration for AI Service

# server:
#   port: 8083

# spring:
#   application:
#     name: ai-service
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017/ai_collection
#       database: ai_collection
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest


# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/


# rabbitmq:
#   exchange:
#     name: activity.exchange
#   queue:
#     name: activity.queue
#   routing:
#     key: activity.routingkey



# gemini:
#   api:
#     url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
#     key: AIzaSyCRkRKMT2Ufve5zMuYuM2wrN0xL6tEHtsk



# # GEMINI_API_URL=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent;

# #GEMINI_API_KEY=AIzaSyCRkRKMT2Ufve5zMuYuM2wrN0xL6tEHtsk;



