spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888


# Application configuration for AI Service

# server:
#   port: 8083

# spring:
#   application:
#     name: ai-service
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017/ai_collection
#       database: ai_collection
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90


# rabbitmq:
#   exchange:
#     name: activity.exchange
#   queue:
#     name: activity.queue
#   routing:
#     key: activity.routingkey



gemini:
  api-key: YOUR_NEW_API_KEY
  endpoint: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

resilience4j:
  retry:
    instances:
      geminiServiceRetry:
        max-attempts: 3
        wait-duration: 1000ms
  circuitbreaker:
    instances:
      geminiServiceCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000ms
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED



