server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: ai-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://configserver:8888}
  data:
    mongodb:
      uri: ${AI_MONGODB_URI:mongodb://mongodb:27017/fitness_ai_db}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

rabbitmq:
  exchange:
    name: ai.exchange
  queue:
    name: ai.queue
  routing:
    key: ai.tracking

gemini:
  api:
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}
    key: ${GEMINI_API_KEY:}
