server: 
  port: ${ACTIVITY_SERVICE_PORT:8082}


spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${ACTIVITY_MONGODB_URI:mongodb://mongodb:27017/fitness_activities_db}
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST:activity-service}
    prefer-ip-address: false


rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
