server: 
  port: 8082


spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/activities_collection
      database: activities_collection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest    

eureka:
  client:
    serviceUrl:
      defaultZone: http://Aniket.mshome.net:8761/eureka/
  instance:
    hostname: Aniket.mshome.net
    prefer-ip-address: false


rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
