server:
  port: 8084


spring:

  application:
    name: ai-service

  data:
    mongodb:
      uri: ${AI_MONGODB_URI:mongodb://mongodb:27017/fitness_ai_db}
      
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}
  instance:
    hostname: ${EUREKA_HOST:ai-service}
    prefer-ip-address: false


rabbitmq:
  exchange:
    name: activity.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking



gemini:
  api:
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}
    key: ${GEMINI_API_KEY:}