management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_DOMAIN}

auth0:
  audience: ${AUTH0_AUDIENCE}

services:
  user: ${USER_SERVICE_URL}
  activity: ${ACTIVITY_SERVICE_URL}
  workout: ${WORKOUT_SERVICE_URL}
