server:
  port: ${PORT:8082}

spring:
  application:
    name: admin-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
    enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:true}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
