server:
  port: ${ADMIN_SERVICE_PORT:8082}

spring:
  application:
    name: admin-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration
