spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888


# --- application.yml ---

# server:
#   port: 8081


# spring:
#   application:
#     name: user-service
#   config:
#     import: optional:configserver:http://localhost:8888
#   datasource:
#     url: jdbc:mysql://127.0.0.1:3306/fitness_users_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: root
#     password: '@ani.8727M'
#   jpa:
#     hibernate:
#       ddl-auto: update
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     show-sql: true


# eureka:
#   client:
#    service-url:
#       defaultZone: http://localhost:8761/eureka/

