server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: user-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://configserver:8888}
  datasource:
    url: ${USER_DB_URL:jdbc:mysql://mysql:3306/fitness_users_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${USER_DB_USERNAME:fitnessuser}
    password: ${USER_DB_PASSWORD:fitness123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8181/realms/fitness-oauth2}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8181/realms/fitness-oauth2/protocol/openid-connect/certs}

eureka:
  instance:
    hostname: ${EUREKA_HOST:user-service}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka/}

# Keycloak Configuration
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8181}
  realm: ${KEYCLOAK_REALM:fitness-oauth2}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:}
    password: ${KEYCLOAK_ADMIN_PASSWORD:}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  integration:
    enabled: true
