spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH0_JWK_SET_URI}
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES:}
    host: ${SPRING_RABBITMQ_HOST:}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:}
    password: ${SPRING_RABBITMQ_PASSWORD:}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:false}
    # If using CloudAMQP, set SPRING_RABBITMQ_ADDRESSES to amqps://... and SSL will be auto-enabled

server:
  port: ${PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  health:
    show-details: always