server:
  port: ${PORT:8083}

spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
    enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:true}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_URI}

