server:
  port: ${ACTIVITY_SERVICE_PORT:8083}

spring:
  application:
    name: activity-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration

