management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  rabbitmq:
    addresses: ${RABBITMQ_URI:}
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    listener:
      simple:
        missing-queues-fatal: false

rabbitmq:
  exchange:
    name: ${RABBITMQ_EXCHANGE:activity.exchange}
  queue:
    name: ${RABBITMQ_QUEUE:activity.queue}
  routing:
    key: ${RABBITMQ_ROUTING_KEY:activity.tracking}
