server:
  port: ${PORT:8083}

spring:
  application:
    name: activity-service
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:}
    enabled: ${SPRING_CLOUD_CONFIG_ENABLED:false}
  autoconfigure:
    exclude: io.sentry.spring.boot.jakarta.SentryAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH0_JWK_SET_URI}
  cloud:
    discovery:
      enabled: ${SPRING_CLOUD_DISCOVERY_ENABLED:false}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    addresses: ${SPRING_RABBITMQ_ADDRESSES}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST}
    ssl:
      enabled: ${SPRING_RABBITMQ_SSL_ENABLED:true}
  rabbitmq.custom:
    queue: activity.queue
    exchange: activity.exchange
    routingKey: activity.tracking
